# Generated by Django 4.1.4 on 2022-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=100)),
                ('learning_mode', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
